# =============================================================
# Task API — Application Configuration
# =============================================================

server:
  port: 8000

spring:
  application:
    name: taskapi
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/taskapi_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver


  flyway:
    # Enable Flyway migrations
    enabled: true

    # Location of migration scripts
    locations: classpath:db/Migration

    # Schema history table name
    table: flyway_schema_history

    # Baseline on migrate for existing database
    baseline-on-migrate: true

    # Validate migrations startup
    validate-on-migrate: true

  # ----- JPA / Hibernate -----
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 9000000
  refresh-token-expiry: 2592000000

rate-limit:
  enabled: true
  auth:
    capacity: 10
    interval: 1m

auth:
  refresh-token-cleanup-interval: PT6H
  refresh-token-cleanup-initial-delay: PT5M

management:
  info:
    build:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics

info:
  app:
    name: ${spring.application.name}
