ALTER TABLE users
    ADD COLUMN role VARCHAR(15);

UPDATE users
SET role = 'USER'
WHERE role IS NULL;

ALTER TABLE users
    ALTER COLUMN role SET DEFAULT 'USER';

ALTER TABLE users
    ALTER COLUMN role SET NOT NULL;

ALTER TABLE tasks
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE tasks
    ALTER COLUMN title SET NOT NULL;
